## **Assignment No -10**

---

**Name** - Wagh Purva Ramesh .
**Roll No** - EN23107132 .
**Class** - TY(B) .
**Batch** - B

---

**Title** -  Text mining: Implement a text mining model to analyze customer reviews and identify sentiments (positive, negative, neutral) and preferences using techniques like sentiment analysis and keyword
extraction.

In [29]:
!pip install rake-nltk

Collecting rake-nltk
  Downloading rake_nltk-1.0.6-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: nltk<4.0.0,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from rake-nltk) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk<4.0.0,>=3.6.2->rake-nltk) (4.67.1)
Downloading rake_nltk-1.0.6-py3-none-any.whl (9.1 kB)
Installing collected packages: rake-nltk
Successfully installed rake-nltk-1.0.6

In [39]:
from numpy import vander
!pip install pandas numpy nltk rake-nltk sci-kit vander

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: rake-nltk in /usr/local/lib/python3.12/dist-packages (1.0.6)
Collecting sci-kit
  Downloading sci_kit-0.1.0-py3-none-any.whl.metadata (631 bytes)
Collecting vander
  Downloading vander-0.1.tar.gz (3.4 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Collecting urwid (from vander)
  Downloading urwid-3.0.3-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from urwid->vander) (0.2.14)
Downloading sci_kit-0.1.0-py3-none-any.whl (3.2 kB)
Downloading urwid-3.0.3-py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.1/296.1 kB 7.8 MB/s eta 0:00:00
Building wheels for collected packages: vander
  Building wheel for vander (setup.py) ... done
  Created wheel for vander: filename=vander-0.1-py3-none-any.whl size=3388 sha256=1c38395ca63afecb33a409f141e54642b8d0eed4d878d3b1dae350e932389579
  Stored in directory: /root/.cache/pip/wheels/bf/d0/f8/81efc0b7c1e9b691c6cf2be34a7ef55c4dc8f9f4fb67793654
Successfully built vander
Installing collected packages: urwid, vander, sci-kit
Successfully installed sci-kit-0.1.0 urwid-3.0.3 vander-0.1

In [40]:
import pandas as pd

try:
    train = pd.read_csv('train.csv', engine='python', on_bad_lines='skip')
    print("Successfully loaded train.csv")
except Exception as e:
    print(f"Error loading train.csv: {e}")
    train = pd.DataFrame()

try:
    test = pd.read_csv('test.csv', engine='python', on_bad_lines='skip')
    print("Successfully loaded test.csv")
except Exception as e:
    print(f"Error loading test.csv: {e}")
    test = pd.DataFrame()

if not train.empty and not test.empty:
    merged_data = pd.concat([train, test], ignore_index=True)
    merged_data.to_csv("customer_reviews.csv", index=False)
    print("Successfully merged train and test data into customer_reviews.csv")
elif train.empty and not test.empty:
    print("train.csv failed to load, so only test.csv was loaded.")
elif not train.empty and test.empty:
    print("test.csv failed to load, so only train.csv was loaded.")
else:
    print("Both train.csv and test.csv failed to load. No merged data created.")

Successfully loaded train.csv
Successfully loaded test.csv
Successfully merged train and test data into customer_reviews.csv

In [41]:
df = pd.read_csv('customer_reviews.csv')

In [42]:
df

            Id                                             Review  Rating
0            1  I have bought several of the Vitality canned d...       5
1            2  Product arrived labeled as Jumbo Salted Peanut...       1
2            3  This is a confection that has been around a fe...       4
3            4  If you are looking for the secret ingredient i...       2
4            5  Great taffy at a great price.  There was a wid...       5
...        ...                                                ...     ...
568449  568450  Great for sesame chicken..this is a good if no...       5
568450  568451  I'm disappointed with the flavor. The chocolat...       2
568451  568452  These stars are small, so you can give 10-15 o...       5
568452  568453  These are the BEST treats for training and rew...       5
568453  568454  I am very satisfied ,product is as advertised,...       5

[568454 rows x 3 columns]

In [43]:
df.shape

(568454, 3)

In [44]:
import pandas as pd
import nltk
import string
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from rake_nltk import Rake

In [45]:
nltk.download('vader_lexicon')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [46]:
df

            Id                                             Review  Rating
0            1  I have bought several of the Vitality canned d...       5
1            2  Product arrived labeled as Jumbo Salted Peanut...       1
2            3  This is a confection that has been around a fe...       4
3            4  If you are looking for the secret ingredient i...       2
4            5  Great taffy at a great price.  There was a wid...       5
...        ...                                                ...     ...
568449  568450  Great for sesame chicken..this is a good if no...       5
568450  568451  I'm disappointed with the flavor. The chocolat...       2
568451  568452  These stars are small, so you can give 10-15 o...       5
568452  568453  These are the BEST treats for training and rew...       5
568453  568454  I am very satisfied ,product is as advertised,...       5

[568454 rows x 3 columns]

In [48]:
sid = SentimentIntensityAnalyzer()

def get_sentiment(text):
    score = sid.polarity_scores(text)['compound']

    if score >= 0.05:
        return "positive"
    elif score <= -0.05:
        return "negative"
    else:
        return "neutral"

df["Sentiment"] = df["Review"].apply(get_sentiment)

In [49]:
df

,Id,Review,Rating,Sentiment
0,1,I have bought several of the Vitality canned d...,5,positive
1,2,Product arrived labeled as Jumbo Salted Peanut...,1,negative
2,3,This is a confection that has been around a fe...,4,positive
3,4,If you are looking for the secret ingredient i...,2,neutral
4,5,Great taffy at a great price. There was a wid...,5,positive
...,...,...,...,...
568449,568450,Great for sesame chicken..this is a good if no...,5,positive
568450,568451,I'm disappointed with the flavor. The chocolat...,2,negative
568451,568452,"These stars are small, so you can give 10-15 o...",5,positive
568452,568453,These are the BEST treats for training and rew...,5,positive
568453,568454,"I am very satisfied ,product is as advertised,...",5,positive

In [50]:
stop_words = set(stopwords.words("english"))

def clean_text(text):
    text = text.lower()
    text = text.translate(str.maketrans("", "", string.punctuation))
    tokens = text.split()
    tokens = [word for word in tokens if word not in stop_words]
    return " ".join(tokens)

df["Clean_Review"] = df["Review"].apply(clean_text)

In [51]:
df

,Id,Review,Rating,Sentiment,Clean_Review
0,1,I have bought several of the Vitality canned d...,5,positive,bought several vitality canned dog food produc...
1,2,Product arrived labeled as Jumbo Salted Peanut...,1,negative,product arrived labeled jumbo salted peanutsth...
2,3,This is a confection that has been around a fe...,4,positive,confection around centuries light pillowy citr...
3,4,If you are looking for the secret ingredient i...,2,neutral,looking secret ingredient robitussin believe f...
4,5,Great taffy at a great price. There was a wid...,5,positive,great taffy great price wide assortment yummy ...
...,...,...,...,...,...
568449,568450,Great for sesame chicken..this is a good if no...,5,positive,great sesame chickenthis good better resturant...
568450,568451,I'm disappointed with the flavor. The chocolat...,2,negative,im disappointed flavor chocolate notes especia...
568451,568452,"These stars are small, so you can give 10-15 o...",5,positive,stars small give 1015 one training session tri...
568452,568453,These are the BEST treats for training and rew...,5,positive,best treats training rewarding dog good groomi...
568453,568454,"I am very satisfied ,product is as advertised,...",5,positive,satisfied product advertised use cereal raw vi...

In [52]:
rake = Rake()

def extract_keywords(text):
    rake.extract_keywords_from_text(text)
    return rake.get_ranked_phrases()[:5]

df["Preferences"] = df["Review"].apply(extract_keywords)

In [54]:
df

,Id,Review,Rating,Sentiment,Clean_Review,Preferences
0,1,I have bought several of the Vitality canned d...,5,positive,bought several vitality canned dog food produc...,"[vitality canned dog food products, smells bet..."
1,2,Product arrived labeled as Jumbo Salted Peanut...,1,negative,product arrived labeled jumbo salted peanutsth...,"[actually small sized unsalted, jumbo salted p..."
2,3,This is a confection that has been around a fe...,4,positive,confection around centuries light pillowy citr...,"[pillowy citrus gelatin, tiny squares, tiny mo..."
3,4,If you are looking for the secret ingredient i...,2,neutral,looking secret ingredient robitussin believe f...,"[root beer extract, secret ingredient, cherry ..."
4,5,Great taffy at a great price. There was a wid...,5,positive,great taffy great price wide assortment yummy ...,"[yummy taffy, wide assortment, taffy lover, gr..."
...,...,...,...,...,...,...
568449,568450,Great for sesame chicken..this is a good if no...,5,positive,great sesame chickenthis good better resturant...,"[sesame chicken .., husband loved, .., .., ..]"
568450,568451,I'm disappointed with the flavor. The chocolat...,2,negative,im disappointed flavor chocolate notes especia...,"[flavor still disappoints, time thanks, small ..."
568451,568452,"These stars are small, so you can give 10-15 o...",5,positive,stars small give 1015 one training session tri...,"[hand smell like dog food, sweet potato flavor..."
568452,568453,These are the BEST treats for training and rew...,5,positive,best treats training rewarding dog good groomi...,"[favorite wet noses treat, sweet potatoes seem..."
568453,568454,"I am very satisfied ,product is as advertised,...",5,positive,satisfied product advertised use cereal raw vi...,"[raw vinegar, general sweetner, use, satisfied..."

In [53]:
print(df[["Id", "Review", "Rating", "Sentiment"]])

            Id                                             Review  Rating  \
0            1  I have bought several of the Vitality canned d...       5
1            2  Product arrived labeled as Jumbo Salted Peanut...       1
2            3  This is a confection that has been around a fe...       4
3            4  If you are looking for the secret ingredient i...       2
4            5  Great taffy at a great price.  There was a wid...       5
...        ...                                                ...     ...
568449  568450  Great for sesame chicken..this is a good if no...       5
568450  568451  I'm disappointed with the flavor. The chocolat...       2
568451  568452  These stars are small, so you can give 10-15 o...       5
568452  568453  These are the BEST treats for training and rew...       5
568453  568454  I am very satisfied ,product is as advertised,...       5

       Sentiment
0       positive
1       negative
2       positive
3        neutral
4       positive
...          ...
568449  positive
568450  negative
568451  positive
568452  positive
568453  positive

[568454 rows x 4 columns]